### ISSUE TITLE
Example sketch does not compile with Arduino 1.0.1

### ISSUE THREAD

**Issue by andrewrapp** [msparks/arduino-ds1302#4]
Compile files: 'const class String' has no member named 'c_str'

This is just an FYI, I don't need a fix. I just changed dayAsString to dayAsInt and moved on. I imagine the Arduino folks made a change to the String implementation. Thanks for providing this library!
